---
- hosts: webservers
  become: true
  tasks:
    - name: Install httpd (Apache)
      ansible.builtin.package:
        name: httpd
        state: present

    - name: Ensure httpd is started and enabled
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true
